### ISSUE TITLE
'int' object is not subscriptable error on line #28 of GPT-2 Train script

### ISSUE THREAD

**Issue by Ghirahim101** [MatthewRayfield/pokemon-gpt-2#1]
This error is currently occurring in the Google Colab copy of the Pokemon GPT-2 Train script #3: Convert Images for Training.

**Comment by MatthewRayfield** [comment]
thanks ! this should be fixed now with 14a082e622dbee0d1b9829556813add31dfd2d6d
( colab was updated too )

if you run into any issues again let me know and a sample input image would be much appreciated 👍

**Comment by MatthewRayfield** [comment]
okay wait... not fixed for certain palette based images... fix incoming...

**Comment by MatthewRayfield** [comment]
okay ! 69b13ee7969aaf19e5a36dd5806666176b65e1bd really fixes this now 🤞
